apiVersion: v1
kind: Service
metadata:
  name: iphoneshop
  labels:
    app: iphoneshop
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: iphoneshop
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: iphoneshop
  annotations:
    kubernetes.io/ingress.global-static-ip-name: iphoneshop-ip
  labels:
    app: iphoneshop
spec:
  defaultBackend:
    service:
      name: iphoneshop-backend
      port:
        number: 8080
---
apiVersion: V1
Kind: Service
metadata:
  name: iphoneshop-backend
  labels:
    app: iphoneshop
  spec:
    type: NodePort
    selector:
      app: iphoneshop
    ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: iphoneshop
spec:
  selector:
    matchLabels:
      app: iphoneshop
    template:
      metadata:
        labels:
          apps: iphoneshop
      spec:
        containers:
        - name: iphoneshop
          image: gcr.io/iphone-shop237-330511/iphoneshop:v1
          imagePullPolicy: Always
          ports:
          - containerPort: 8080